export const ADD_USER = 'ADD_USER';


export const FETCH_CRAD_LIST = 'FETCH_CRAD_LIST';
export const FETCH_CRAD_LIST_RESOLVED = 'FETCH_CRAD_LIST_RESOLVED';
export const FETCH_CRAD_LIST_REJECTED = 'FETCH_CRAD_LIST_REJECTED';
export const REMOVE_CARD_LIST = 'REMOVE_CARD_LIST';